In [33]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import BaggingClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import roc_auc_score
from sklearn.metrics import recall_score
from sklearn.metrics import  f1_score
from sklearn.metrics import precision_score
from sklearn.metrics import confusion_matrix
from xgboost import XGBClassifier
import random
import time
import sys
import warnings
warnings.filterwarnings("ignore")

np.random.seed(123)

In [34]:
df = pd.read_csv("diabetes.csv")
df.head(5)

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  DiabetesPedigreeFunction  Age  Outcome
0            6      148             72             35        0  33.6                     0.627   50        1
1            1       85             66             29        0  26.6                     0.351   31        0
2            8      183             64              0        0  23.3                     0.672   32        1
3            1       89             66             23       94  28.1                     0.167   21        0
4            0      137             40             35      168  43.1                     2.288   33        1

In [35]:
df.dropna(inplace=True)
df.shape

(768, 9)

In [36]:
target  = np.array(df["Outcome"])
df = df.drop("Outcome", axis=1)
df_list = list(df.columns)
df_list

['Pregnancies',
 'Glucose',
 'BloodPressure',
 'SkinThickness',
 'Insulin',
 'BMI',
 'DiabetesPedigreeFunction',
 'Age']

In [37]:
df.shape

(768, 8)

In [38]:
train_x, test_x, train_y, test_y = train_test_split(df, target, test_size=0.2, random_state=42)

In [39]:
# Best Score (Bagging)
"""[[131  15]
 [ 36  49]]
Accuracy: 0.7792207792207793
Auc Score Prob 0.8764705882352941
Recall: 0.5764705882352941
Precission: 0.765625
F1 Score: 0.6577181208053692
"""

'[[131  15]\n [ 36  49]]\nAccuracy: 0.7792207792207793\nAuc Score Prob 0.8764705882352941\nRecall: 0.5764705882352941\nPrecission: 0.765625\nF1 Score: 0.6577181208053692\n'

In [40]:
# RandomForest Performance
"""[[130  16]
 [ 34  51]]
Accuracy: 0.7835497835497836
Auc Score: 0.7452054794520548
Auc Score Prob: 0.8638195004029009
Recall 0.6
Precission: 0.7611940298507462
F1 Score: 0.6710526315789473
"""

'[[130  16]\n [ 34  51]]\nAccuracy: 0.7835497835497836\nAuc Score: 0.7452054794520548\nAuc Score Prob: 0.8638195004029009\nRecall 0.6\nPrecission: 0.7611940298507462\nF1 Score: 0.6710526315789473\n'

In [41]:
xg = XGBClassifier(objective="binary:logistic")
xg.fit(train_x, train_y, eval_metric="auc")
pred = xg.predict(test_x)
pred_prob = xg.predict_proba(test_x)[:1]
print(confusion_matrix(test_y, pred))
print("Accuracy:", accuracy_score(test_y, pred))
print("Auc Score:", roc_auc_score(test_y, pred))
print("Recall:", recall_score(test_y, pred))
print("Precission:", precision_score(test_y, pred))
print("F1 Score:", f1_score(test_y, pred))
# Bad Performance
# XGBoost A better method for big data

[[70 29]
 [19 36]]
Accuracy: 0.6883116883116883
Auc Score: 0.6808080808080808
Recall: 0.6545454545454545
Precission: 0.5538461538461539
F1 Score: 0.6000000000000001
